from __future__ import annotations

import csv
import io
import json
import os
import re
import tomllib
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from uuid import uuid4

from stockrank.config import (
    COMPONENTS,
    LOCAL_PREFERENCES_PATH,
    VALID_HORIZONS,
    VALID_PROFILES,
    VALID_RISK_LEVELS,
    VALID_SECTORS,
    load_settings,
    scoring_fingerprint,
    universe_fingerprint,
)
from stockrank.data import YFinanceProvider
from stockrank.models import Security

LOCAL_UNIVERSE_PATH = Path("config/universe.local.csv")
PROFILE_NAMES = VALID_PROFILES
HORIZONS = VALID_HORIZONS
RISK_LEVELS = VALID_RISK_LEVELS

PROFILE_WEIGHTS: dict[str, dict[str, float]] = {
    "balanced": {
        "growth": 0.25,
        "valuation": 0.20,
        "quality": 0.25,
        "momentum": 0.20,
        "risk": 0.10,
    },
    "growth": {"growth": 0.40, "valuation": 0.10, "quality": 0.25, "momentum": 0.15, "risk": 0.10},
    "value": {"growth": 0.15, "valuation": 0.40, "quality": 0.25, "momentum": 0.10, "risk": 0.10},
    "quality": {"growth": 0.20, "valuation": 0.15, "quality": 0.40, "momentum": 0.10, "risk": 0.15},
    "momentum": {
        "growth": 0.20,
        "valuation": 0.10,
        "quality": 0.15,
        "momentum": 0.40,
        "risk": 0.15,
    },
    "lower_volatility": {
        "growth": 0.15,
        "valuation": 0.15,
        "quality": 0.30,
        "momentum": 0.10,
        "risk": 0.30,
    },
}

RISK_MULTIPLIERS = {
    "conservative": {
        "growth": 0.85,
        "valuation": 1.10,
        "quality": 1.15,
        "momentum": 0.80,
        "risk": 1.50,
    },
    "moderate": {component: 1.0 for component in COMPONENTS},
    "aggressive": {
        "growth": 1.15,
        "valuation": 0.90,
        "quality": 0.90,
        "momentum": 1.20,
        "risk": 0.60,
    },
}

HORIZON_MULTIPLIERS = {
    "short": {"growth": 0.85, "valuation": 0.90, "quality": 0.85, "momentum": 1.35, "risk": 1.00},
    "medium": {component: 1.0 for component in COMPONENTS},
    "long": {"growth": 1.15, "valuation": 1.00, "quality": 1.15, "momentum": 0.60, "risk": 1.05},
}

YAHOO_SECTOR_MAP = {
    "Basic Materials": "Materials",
    "Communication Services": "Communication Services",
    "Consumer Cyclical": "Consumer Discretionary",
    "Consumer Defensive": "Consumer Staples",
    "Energy": "Energy",
    "Financial Services": "Financials",
    "Healthcare": "Health Care",
    "Industrials": "Industrials",
    "Real Estate": "Real Estate",
    "Technology": "Information Technology",
    "Utilities": "Utilities",
}


class PersonalizationUpdateError(RuntimeError):
    """Raised when local personalization cannot be safely applied or restored."""


@dataclass
class _FileChange:
    path: Path
    content: str | None
    staged: Path | None = None
    backup: Path | None = None
    installed: bool = False


def _next_backup_path(path: Path) -> Path:
    index = 0
    while True:
        suffix = ".bak" if index == 0 else f".bak.{index}"
        candidate = path.with_name(path.name + suffix)
        if not candidate.exists():
            return candidate
        index += 1


def _stage_text(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    staged = path.with_name(f"{path.name}.{uuid4().hex}.tmp")
    try:
        staged.write_text(content, encoding="utf-8")
    except Exception:
        try:
            staged.unlink(missing_ok=True)
        except OSError:
            pass
        raise
    return staged


def _backup_active_file(path: Path, backup: Path) -> None:
    os.replace(path, backup)


def _install_staged_file(staged: Path, path: Path) -> None:
    os.replace(staged, path)


def _restore_backup_file(backup: Path, path: Path) -> None:
    os.replace(backup, path)


def _preserve_unbacked_active_file(path: Path) -> Path:
    recovery = path.with_name(f"{path.name}.failed.{uuid4().hex}")
    os.replace(path, recovery)
    return recovery


def _reload_local_customization(root: Path) -> None:
    load_settings(root)


def _render_local_universe(securities: Iterable[Security]) -> str:
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(("ticker", "company", "sector"))
    for security in securities:
        writer.writerow((security.ticker, security.company, security.sector))
    return output.getvalue()


def _render_local_preferences(
    *,
    profile: str,
    horizon: str,
    risk: str,
    weights: dict[str, float],
    model_version: str,
    universe_name: str,
    universe_path: str,
    candidate_limit: int,
    minimum_score: float,
    minimum_coverage: float,
) -> str:
    weight_lines = "\n".join(f"{component} = {weights[component]:.12f}" for component in COMPONENTS)
    return f"""# Personal settings generated by `stockrank configure`.
# This file is local to this computer and intentionally ignored by Git.

[app]
top_candidate_limit = {candidate_limit}
minimum_candidate_score = {minimum_score:.6g}
minimum_overall_coverage = {minimum_coverage:.6g}

[universe]
name = {json.dumps(universe_name)}
path = {json.dumps(universe_path)}
maintenance_mode = "user_approved_manual"

[preferences]
profile = {json.dumps(profile)}
investment_horizon = {json.dumps(horizon)}
risk_tolerance = {json.dumps(risk)}

[scoring]
model_version = {json.dumps(model_version)}

[scoring.overall]
{weight_lines}
"""


def _validate_staged_personalization(root: Path, changes: list[_FileChange]) -> None:
    by_path = {change.path.resolve(): change for change in changes}
    preferences = by_path.get((root / LOCAL_PREFERENCES_PATH).resolve())
    if preferences is None or preferences.staged is None:
        return
    parsed = tomllib.loads(preferences.staged.read_text(encoding="utf-8"))
    universe = parsed.get("universe")
    if not isinstance(universe, dict) or not isinstance(universe.get("path"), str):
        raise TypeError("staged personal preferences do not define universe.path")
    configured = Path(universe["path"])
    configured = configured if configured.is_absolute() else root / configured
    universe_change = by_path.get(configured.resolve())
    universe_source = (
        universe_change.staged
        if universe_change is not None and universe_change.staged is not None
        else configured
    )
    if universe_source is None or not universe_source.is_file():
        raise ValueError(f"staged personal universe does not exist: {configured}")
    if not read_universe_input(universe_source):
        raise ValueError("staged personal universe is empty")


def _cleanup_staged_files(changes: Iterable[_FileChange]) -> None:
    for change in changes:
        if change.staged is None:
            continue
        try:
            change.staged.unlink(missing_ok=True)
        except OSError:
            pass


def _rollback_file_changes(changes: list[_FileChange]) -> tuple[list[str], list[Path]]:
    errors: list[str] = []
    recovery_files: list[Path] = []
    for change in reversed(changes):
        if change.backup is not None and change.backup.exists():
            try:
                _restore_backup_file(change.backup, change.path)
            except OSError as exc:
                errors.append(f"{change.path}: {exc}")
            continue
        if change.installed and change.path.exists():
            try:
                recovery_files.append(_preserve_unbacked_active_file(change.path))
            except OSError as exc:
                errors.append(f"{change.path}: {exc}")
    return errors, recovery_files


def _apply_local_file_transaction(root: Path, changes: list[_FileChange]) -> list[Path]:
    if not changes:
        return []
    application_started = False
    try:
        for change in changes:
            if change.content is not None:
                change.staged = _stage_text(change.path, change.content)
        _validate_staged_personalization(root, changes)

        application_started = True
        for change in changes:
            if change.path.exists():
                change.backup = _next_backup_path(change.path)
                _backup_active_file(change.path, change.backup)
            if change.staged is not None:
                _install_staged_file(change.staged, change.path)
                change.installed = True
        _reload_local_customization(root)
    except Exception as exc:
        if not application_started:
            _cleanup_staged_files(changes)
            raise PersonalizationUpdateError(
                f"Personalization could not be staged or validated: {exc}. No active files changed."
            ) from exc
        rollback_errors, recovery_files = _rollback_file_changes(changes)
        _cleanup_staged_files(changes)
        if rollback_errors:
            preserved = [
                str(change.backup)
                for change in changes
                if change.backup is not None and change.backup.exists()
            ]
            preserved.extend(str(path) for path in recovery_files)
            locations = ", ".join(preserved) if preserved else "none detected"
            raise PersonalizationUpdateError(
                "RECOVERY REQUIRED: personalization failed and automatic restoration "
                f"was incomplete. Preserved recovery files: {locations}. "
                f"Original error: {exc}. Rollback error(s): {'; '.join(rollback_errors)}"
            ) from exc
        raise PersonalizationUpdateError(
            f"Personalization failed: {exc}. Prior configuration restored."
        ) from exc
    _cleanup_staged_files(changes)
    return [change.backup for change in changes if change.backup is not None]


def profile_weights(profile: str, risk: str, horizon: str) -> dict[str, float]:
    if profile not in PROFILE_WEIGHTS:
        raise ValueError("Unknown profile: " + profile)
    if risk not in RISK_LEVELS:
        raise ValueError("Unknown risk tolerance: " + risk)
    if horizon not in HORIZONS:
        raise ValueError("Unknown investment horizon: " + horizon)
    adjusted = {
        component: (
            PROFILE_WEIGHTS[profile][component]
            * RISK_MULTIPLIERS[risk][component]
            * HORIZON_MULTIPLIERS[horizon][component]
        )
        for component in COMPONENTS
    }
    total = sum(adjusted.values())
    return {component: adjusted[component] / total for component in COMPONENTS}


def parse_component_weights(value: str) -> dict[str, float]:
    try:
        weights = {
            key.strip(): float(raw.strip())
            for item in value.split(",")
            for key, raw in [item.split("=", 1)]
        }
    except (TypeError, ValueError) as exc:
        raise ValueError(
            "Weights must look like growth=.25,valuation=.20,quality=.25,momentum=.20,risk=.10"
        ) from exc
    if set(weights) != set(COMPONENTS):
        raise ValueError("Custom weights must define exactly: " + ", ".join(COMPONENTS))
    if any(weight < 0 for weight in weights.values()) or not abs(sum(weights.values()) - 1) < 1e-6:
        raise ValueError("Custom weights must be nonnegative and total 1.0")
    return weights


def model_identifier(profile: str, scoring: dict[str, Any], weights: dict[str, float]) -> str:
    payload = dict(scoring)
    payload.pop("model_version", None)
    payload["overall"] = weights
    digest = scoring_fingerprint(payload)
    return f"custom-{profile}-{digest}"


def universe_identifier(securities: Iterable[Security]) -> str:
    values = list(securities)
    digest = universe_fingerprint(values)
    return f"custom-{len(values)}-{digest}"


def parse_tickers(value: str) -> list[str]:
    tickers = [item.strip().upper() for item in value.replace("\n", ",").split(",")]
    return list(dict.fromkeys(ticker for ticker in tickers if ticker))


def read_universe_input(path: Path) -> list[Security]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if not reader.fieldnames or "ticker" not in reader.fieldnames:
            raise ValueError("Universe input CSV requires a ticker column")
        output = []
        for row in reader:
            ticker = (row.get("ticker") or "").strip().upper()
            if not ticker:
                continue
            output.append(
                Security(
                    ticker=ticker,
                    company=(row.get("company") or "").strip(),
                    sector=(row.get("sector") or "").strip(),
                )
            )
    return output


def enrich_universe(
    securities: Iterable[Security], provider: YFinanceProvider | None = None
) -> tuple[list[Security], list[str]]:
    provider = provider or YFinanceProvider()
    output: list[Security] = []
    warnings: list[str] = []
    for security in securities:
        if security.company and security.sector in VALID_SECTORS:
            output.append(security)
            continue
        snapshot, provider_warnings = provider.fetch_fundamental(security)
        warnings.extend(provider_warnings)
        yahoo_sector = snapshot.sector if snapshot else None
        sector = (
            security.sector
            if security.sector in VALID_SECTORS
            else YAHOO_SECTOR_MAP.get(security.sector, "")
            or YAHOO_SECTOR_MAP.get(yahoo_sector or "", "")
        )
        company = security.company or (snapshot.company if snapshot else None) or ""
        output.append(Security(security.ticker, company, sector))
        if not company or sector not in VALID_SECTORS:
            warnings.append(
                f"{security.ticker}: company/sector could not be validated; use a CSV with manual values"
            )
    return output, warnings


def save_local_customization(
    root: Path,
    *,
    securities: Iterable[Security] | None,
    profile: str,
    horizon: str,
    risk: str,
    weights: dict[str, float],
    model_version: str,
    universe_name: str,
    universe_path: str,
    candidate_limit: int,
    minimum_score: float,
    minimum_coverage: float,
) -> tuple[Path, list[Path]]:
    preferences_path = root / LOCAL_PREFERENCES_PATH
    changes: list[_FileChange] = []
    if securities is not None:
        changes.append(
            _FileChange(
                path=root / LOCAL_UNIVERSE_PATH,
                content=_render_local_universe(securities),
            )
        )
    changes.append(
        _FileChange(
            path=preferences_path,
            content=_render_local_preferences(
                profile=profile,
                horizon=horizon,
                risk=risk,
                weights=weights,
                model_version=model_version,
                universe_name=universe_name,
                universe_path=universe_path,
                candidate_limit=candidate_limit,
                minimum_score=minimum_score,
                minimum_coverage=minimum_coverage,
            ),
        )
    )
    backups = _apply_local_file_transaction(root, changes)
    return preferences_path, backups


def reset_local_customization(root: Path) -> list[Path]:
    changes: list[_FileChange] = []
    for relative in (LOCAL_PREFERENCES_PATH, LOCAL_UNIVERSE_PATH):
        path = root / relative
        if path.exists():
            changes.append(_FileChange(path=path, content=None))
    return _apply_local_file_transaction(root, changes)


def activate_proposed_universe(
    root: Path,
    securities: list[Security],
    *,
    version: str,
    receipt_path: Path,
    receipt: dict,
    discovery_policy: dict | None = None,
) -> list[Path]:
    """Change only the universe table; preserve all unrelated personal settings verbatim.

    Membership and the approval receipt participate in the existing rollback transaction.
    The immutable version file is intentionally distinct from manual customization.
    """
    if not re.fullmatch(r"discovery-[a-f0-9]{16}", version):
        raise ValueError("Invalid proposed universe version")
    relative = Path(f"config/universe.{version}.local.csv")
    if (root / relative).exists():
        raise ValueError("This universe version already exists; inspect its approval receipt")
    preferences_path = root / LOCAL_PREFERENCES_PATH
    existing = preferences_path.read_text(encoding="utf-8") if preferences_path.exists() else ""
    section = (
        "[universe]\n"
        f"name = {json.dumps(version)}\npath = {json.dumps(relative.as_posix())}\n"
        'maintenance_mode = "user_approved_proposal"\n\n'
    )
    pattern = r"(?m)^\[universe\][ \t]*(?:#[^\n]*)?\r?\n[\s\S]*?(?=^\[|\Z)"
    if re.search(pattern, existing):
        updated = re.sub(pattern, lambda _: section, existing, count=1)
    else:
        updated = existing.rstrip() + "\n\n" + section
    parsed = tomllib.loads(updated)
    if parsed["universe"]["name"] != version:
        raise ValueError("Could not safely update personal universe table")
    changes = [
        _FileChange(root / relative, _render_local_universe(securities)),
        _FileChange(preferences_path, updated),
        _FileChange(receipt_path, json.dumps(receipt, indent=2) + "\n"),
    ]
    if discovery_policy is not None:
        changes.append(
            _FileChange(
                root / "config/universe-discovery.local.json",
                json.dumps(discovery_policy, indent=2) + "\n",
            )
        )
    return _apply_local_file_transaction(root, changes)
